### ISSUE TITLE
Lack of raws' explanation

### ISSUE THREAD

**Issue by lynnporu** [walmes/Tikz#1]
I've tried to compile [dist_normal_tab](https://github.com/walmes/Tikz/blob/master/src/dist_normal_tab.pgf) file, but it gives up on the following error:
```
! Package pgfkeys Error: I do not know the key '/tikz/matrix of nodes' and I am
 going to ignore it. Perhaps you misspelled it.
```

Same issues related to undefined figures or illegal parameters appears on almost all files you have in this repo. It becomes quiet painful to come through all references and stackoverflow answers to find preamble I should use. Please, consider of declaring used pgfplots/tikz libraries, compatibility parameters or at least tools you were using for compiling (pdflatex, lualatex, etc).

**Comment by walmes** [comment]
@lynnporu, thank you for the notification.

Please, check the content of the file [./src/TIKZ_PREAMBLE.pgs](https://github.com/walmes/Tikz/blob/master/src/TIKZ_PREAMBLE.pgs) because it works as the main preamble for compiling each figure. Its is quite general and work and should work for any figure in this repo.
I use [Ktikz](http://www.hackenberger.at/blog/ktikz-editor-for-the-tikz-language/) do edit figures. I declare the file used as preamble in Ktikz. The editor generates the figure on the fly.
I appreciate your suggestions and I will specify libraries and requirements for the next figures.

**Comment by lynnporu** [comment]
@walmes, oh, I see, you've already mentioned `TIKZ_PREAMBLE.pgs` in your readme file. Accidentally I just skipped the very top of the text, because the file is too large. Sorry.

You've done a very good job, anyway. I really like your illustrations. Have a nice day :)
